name: dental_record_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.3.1+8

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 일반 패키지들
  http: ^1.2.1
  cupertino_icons: ^1.0.8
  path: ^1.9.0
  shared_preferences: ^2.3.3
  url_launcher: ^6.2.6
  photo_view: ^0.15.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  pdf: ^3.11.0
  flutter_file_dialog: ^3.0.2
  printing: ^5.13.4
  path_provider: ^2.1.4
  dio: ^5.7.0
  pdfx: ^2.6.0
  video_player: ^2.8.6
  chewie: ^1.8.1

  # 충돌을 일으키는 Firebase 패키지들을 최신 안정 버전으로 통일했습니다.
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  firebase_auth: ^6.0.2

  connectivity_plus: ^6.0.0

  # 다른 패키지들
  provider: ^6.1.2
  file_picker: ^10.3.3

# 특정 종속성 충돌을 해결하기 위한 부분.
dependency_overrides:
  package_info_plus: ^8.0.2
  wakelock_plus: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - lib/data/prosthesis_tree.json
    - assets/fonts/NotoSansKR-Regular.ttf
  uses-material-design: true